### ISSUE TITLE
Single Date Picker, Like, one way or two way flight

### ISSUE THREAD

**Issue by AmirJavaidSwe** [joffreyBerrier/vue-datepicker#39]
can you add a feature that a user can only pick a single date, like a one-way flight trip or cab booking?

**Comment by joffreyBerrier** [comment]
Hi @AmirJavaidSwe yes I'm looking that this week !

**Comment by AmirJavaidSwe** [comment]
@joffreyBerrier any updates on this?

**Comment by joffreyBerrier** [comment]
Hi @AmirJavaidSwe sorry for delay :/ But now you can have one calendar using this props : `single-calendar` to true 👍🏻
