### ISSUE TITLE
Month names translation

### ISSUE THREAD

**Issue by cumalikaya** [joffreyBerrier/vue-datepicker#47]
Hi, thanks for this package, quite useful. I have a problem with the translation. 

For Turkish language, calendarLanguage = {
  tr: {
    clearDates: "temizle",
    close: "Kapat",
    week: "hafta",
    weeks: "haftalar",
    days: {
      monday: "Pzt",
      tuesday: "Sal",
      wednesday: "Çar",
      thursday: "Per",
      friday: "Cuma",
      saturday: "Cmt",
      sunday: "Paz",
    },
    months: {
      january: "Ocak",
      february: "Şubat",
      march: "Mart",
      april: "Nisan",
      may: "Mayıs",
      june: "Haziran",
      july: "Temmuz",
      august: "Ağustos",
      september: "Eylül",
      october: "Ekim",
      november: "Kasım",
      december: "Aralık",
    },
    today: "Bugün",
    periodType: {
      weeklyBySaturday: "Cumartesi'den Cumartesi'ye",
      weeklyBySunday: "Pazar'dan Pazar'a",
      weeklyByMonday: "Pazartesi'den Pazartesi'ne",
      nightly: "Minimum %{minimumDuration} gece",
    },
    halfDay: {
      checkIn: "Çıkış günü",
      checkOut: "Giriş günü",
    },
  }
} 

I defined a variable like this. But I cannot translate the month names into Turkish. How should I solve this?

**Comment by joffreyBerrier** [comment]
Hi @cumalikaya, to use translations, you need to define a **props translations** with a key and an object.
In this example, the key is **en**.

The object needs to follow this structure:
```js
en: {
  clearDates: "Clear dates",
  close: "Close",
  days: {
    monday: "Mo",
    tuesday: "Tu",
    wednesday: "We",
    thursday: "Th",
    friday: "Fr",
    saturday: "Sa",
    sunday: "Su",
  },
  today: "Today",
  periodType: {
    weeklyBySaturday: "From Saturday to Saturday",
    weeklyBySunday: "From Sunday to Sunday",
    weeklyByMonday: "From Monday to Monday",
    nightly: "A minimum of %{minimumDuration} night is required",
  },
  halfDay: {
    checkIn: "Possible end of stay",
    checkOut: "Possible start of stay",
  },
},
```

Now, set the **props locale** with the name of the key, in your case, **tr**
